baseURL = "https://blog.wenzl.no/"
defaultContentLanguage = "no"
defaultContentLanguageInSubdir = true
title = "Den magre eremitt og andre eventyr"

[languages]
  [languages.no]
    locale = "nb-NO"
    weight = 1
    title = "Den magre eremitt og andre eventyr"
    [languages.no.params]
      description = "Den magre eremitt og andre eventyr"
      tagline = "Martin Wenzl"

  [languages.cs]
    locale = "cs-CZ"
    weight = 2
    title = "Chudy poustevník a jiné pohádky"
    [languages.cs.params]
      description = "Chudy poustevník a jiné pohádky"
      tagline = "Martin Wenzl"

  [languages.en]
    locale = "en-US"
    weight = 3
    title = "The Lean Hermit and Other Tales"
    [languages.en.params]
      description = "The Lean Hermit and Other Tales"
      tagline = "Martin Wenzl"

paginate = 10
summaryLength = 70

[taxonomies]
  category = "categories"
  tag      = "tags"

[params]
  description = "Den magre eremitt og andre eventyr"
  author      = "Martin Wenzl"
  tagline     = "Martin Wenzl"
  siteURL     = "https://blog.wenzl.no"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "static/images"
    target = "assets/images"
